# Generated by Django 3.1.13 on 2022-04-19 05:55

import data_export.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=2048, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time', verbose_name='created at')),
                ('file', models.FileField(null=True, upload_to='export')),
                ('md5', models.CharField(default='', max_length=128, verbose_name='md5 of file')),
                ('finished_at', models.DateTimeField(default=None, help_text='Complete or fail time', null=True, verbose_name='finished at')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('failed', 'Failed'), ('completed', 'Completed')], default='created', max_length=64, verbose_name='Export status')),
                ('counters', models.JSONField(default=dict, verbose_name='Exporting meta data')),
            ],
            bases=(data_export.mixins.ExportMixin, models.Model),
        ),
    ]
