# Generated by Django 3.1.13 on 2022-06-28 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_import', '0003_fileupload_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20220628_2121'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklock',
            name='user',
            field=models.ForeignKey(help_text='User who locked this task', on_delete=django.db.models.deletion.CASCADE, related_name='task_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='file_upload',
            field=models.ForeignKey(blank=True, help_text='Uploaded file used as data source for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='data_import.fileupload'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='Project ID for this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='annotationdraft',
            name='annotation',
            field=models.ForeignKey(blank=True, help_text='Corresponding annotation for this draft', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='tasks.annotation'),
        ),
        migrations.AddField(
            model_name='annotationdraft',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Corresponding task for this draft', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='annotationdraft',
            name='user',
            field=models.ForeignKey(help_text='User who created this draft', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='completed_by',
            field=models.ForeignKey(help_text='User ID of the person who created this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='parent_annotation',
            field=models.ForeignKey(help_text='Points to the parent annotation from which this annotation was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_annotations', to='tasks.annotation'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='parent_prediction',
            field=models.ForeignKey(help_text='Points to the prediction from which this annotation was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_annotations', to='tasks.prediction'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='task',
            field=models.ForeignKey(help_text='Corresponding task for this annotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'is_labeled'], name='task_project_6acf5f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['id', 'overlap'], name='task_id_7a9aca_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['overlap'], name='task_overlap_6a196e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_labeled'], name='task_is_labe_215a18_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['task', 'ground_truth'], name='task_comple_task_id_e82920_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['was_cancelled'], name='task_comple_was_can_f87d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['ground_truth'], name='task_comple_ground__088a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['created_at'], name='task_comple_created_f55e6f_idx'),
        ),
    ]
