# Generated by Django 3.1.13 on 2022-05-25 06:09

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='sch title')),
                ('dataset', models.CharField(max_length=1000, verbose_name='sch dataset')),
                ('inf_model', models.CharField(max_length=1000, verbose_name='sch inference model')),
                ('period', models.CharField(max_length=1000, verbose_name='sch period')),
                ('tmp_auto_remove', models.BooleanField(default=False, verbose_name='sch temp auto removed')),
                ('prj_auto_create', models.BooleanField(default=False, verbose_name='sch prj auto created')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'db_table': 'sch',
            },
            bases=(core.mixins.DummyModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SchMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Sch member is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sch', models.ForeignKey(help_text='Project ID', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='schs.sch')),
            ],
        ),
    ]
