# Generated by Django 3.1.13 on 2022-05-25 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20220525_0609'),
        ('schs', '0001_initial'),
        ('organizations', '0002_auto_20220525_0609'),
        ('ml', '0002_mlbackend_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='schmember',
            name='user',
            field=models.ForeignKey(help_text='User ID', on_delete=django.db.models.deletion.CASCADE, related_name='sch_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schs', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='sch',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schs_model', to='ml.mlbackend'),
        ),
        migrations.AddField(
            model_name='sch',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='sch',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schs_prj', to='projects.project'),
        ),
    ]
