# Generated by Django 3.1.13 on 2022-04-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='project',
            field=models.ForeignKey(help_text='Project ID', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='projects.project'),
        ),
    ]
