# Generated by Django 3.1.13 on 2022-04-08 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_manager', '0002_view_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='user',
            field=models.ForeignKey(help_text='User who made this view', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filtergroup',
            name='filters',
            field=models.ManyToManyField(help_text='Connected filters', related_name='filter_groups', to='data_manager.Filter'),
        ),
    ]
