# Generated by Django 3.1.13 on 2022-06-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('io_storages', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3importstoragelink',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_s3importstoragelink', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='s3importstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_s3importstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='s3exportstoragelink',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_s3exportstoragelink', to='tasks.annotation'),
        ),
        migrations.AddField(
            model_name='s3exportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.s3exportstorage'),
        ),
        migrations.AddField(
            model_name='s3exportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_s3exportstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='redisimportstoragelink',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_redisimportstoragelink', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='redisexportstoragelink',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_redisexportstoragelink', to='tasks.annotation'),
        ),
        migrations.AddField(
            model_name='localfilesimportstoragelink',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_localfilesimportstoragelink', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='localfilesexportstoragelink',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_localfilesexportstoragelink', to='tasks.annotation'),
        ),
        migrations.AddField(
            model_name='gcsimportstoragelink',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_gcsimportstoragelink', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='gcsexportstoragelink',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_gcsexportstoragelink', to='tasks.annotation'),
        ),
        migrations.AddField(
            model_name='azureblobimportstoragelink',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_azureblobimportstoragelink', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='azureblobexportstoragelink',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_azureblobexportstoragelink', to='tasks.annotation'),
        ),
        migrations.AddField(
            model_name='redisimportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.redisimportstorage'),
        ),
        migrations.AddField(
            model_name='redisimportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_redisimportstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='redisexportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.redisexportstorage'),
        ),
        migrations.AddField(
            model_name='redisexportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_redisexportstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='localfilesimportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.localfilesimportstorage'),
        ),
        migrations.AddField(
            model_name='localfilesimportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_localfilesimportstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='localfilesexportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.localfilesexportstorage'),
        ),
        migrations.AddField(
            model_name='localfilesexportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_localfilesexportstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='gcsimportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.gcsimportstorage'),
        ),
        migrations.AddField(
            model_name='gcsimportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_gcsimportstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='gcsexportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.gcsexportstorage'),
        ),
        migrations.AddField(
            model_name='gcsexportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_gcsexportstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='azureblobimportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.azureblobimportstorage'),
        ),
        migrations.AddField(
            model_name='azureblobimportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_azureblobimportstorages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='azureblobexportstoragelink',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.azureblobexportstorage'),
        ),
        migrations.AddField(
            model_name='azureblobexportstorage',
            name='project',
            field=models.ForeignKey(help_text='A unique integer value identifying this project.', on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_azureblobexportstorages', to='projects.project'),
        ),
    ]
